### ISSUE TITLE
Unable to Run this application

### ISSUE THREAD

**Issue by muku007-codes** [Sk4467/Proton-Screening-Test#1]
**I got this error while running the server ⁉️**

`[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
MongoDB Connect Failed :  TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (D:\DEV\Proton-Screening-Test\server\node_modules\mongodb-connection-string-url\lib\index.js:9:30)
    at new ConnectionString (D:\DEV\Proton-Screening-Test\server\node_modules\mongodb-connection-string-url\lib\index.js:85:34)
    at parseOptions (D:\DEV\Proton-Screening-Test\server\node_modules\mongodb\lib\connection_string.js:204:17)
    at new MongoClient (D:\DEV\Proton-Screening-Test\server\node_modules\mongodb\lib\mongo_client.js:46:63)
    at MongoClient.connect (D:\DEV\Proton-Screening-Test\server\node_modules\mongodb\lib\mongo_client.js:231:24)
    at connectDB (file:///D:/DEV/Proton-Screening-Test/server/db/connection.js:7:38)
    at file:///D:/DEV/Proton-Screening-Test/server/app.js:30:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
(node:22104) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)`
Thanks in advance 🙏🏻

**Comment by MahindraGamini** [comment]
Yes I am also getting the same error i think the aws is in the maintainance mode

**Comment by muku007-codes** [comment]
May be you were right but what should we do now??

**Comment by bansalankit01** [comment]
please someone ask them to provide us the .env file as well

**Comment by pranjalee30** [comment]
Unable to run this app.

**Comment by VimalBharti99** [comment]
got same error.

**Comment by prynsu07github** [comment]
I don't think project will run without.env file

**Comment by MurtAz2001** [comment]
I am also getting same error

**Comment by VedangKanade20** [comment]
I was able to run the project guys 
Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders
Now make sure to place the env file not in route folder but in the server folder itself
Now make sure you enter the details in env file correctly and now connect it to your mongodb
![Screenshot (54)](https://github.com/Sk4467/Proton-Screening-Test/assets/123882577/dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d)

**Comment by MurtAz2001** [comment]
> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDUwNzYsIm5iZiI6MTcxODAwNDc3NiwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzMyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGM4ZTNiMDcwMzI2MmU2MGIzMWQ2OTEwYmNmZmI2N2VlOWNkMTViYTVhZjMzNDFjODU3NDQ4NWY3MDVlNGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u54jEI7ZGCJ9ui0eNPj80if6LkrLYchfcA0raLtSZxE)

but .env file is missing?

**Comment by shadow855** [comment]
use localhost guys

**Comment by prynsu07github** [comment]
> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY0NDksIm5iZiI6MTcxODAwNjE0OSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNlZjViM2QzNTE1Njc2NmE4Njk1MzljMDcxYjE1Njc0MjQ4YTBkZjU1OTJmOGE1ZDI0NzcxNjE1YTI0ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msGpmd4QB8iKZjjt0WBJDtsyslxenCrrGeWyxcNoOmA)



> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY0NDksIm5iZiI6MTcxODAwNjE0OSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNlZjViM2QzNTE1Njc2NmE4Njk1MzljMDcxYjE1Njc0MjQ4YTBkZjU1OTJmOGE1ZDI0NzcxNjE1YTI0ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msGpmd4QB8iKZjjt0WBJDtsyslxenCrrGeWyxcNoO

> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY1MzksIm5iZiI6MTcxODAwNjIzOSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Nzc5OWQ5MGNlZGMxNjIxYjk1YWM5ZDliNGU1OTFlNDM0Njg5NTBhMDM5NjAxYzA2ZWZhMDQ5YTFkNDZjZGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1HTkj3TETZzw343fOZT-1Y1LsRGGCKwrklmlwi-lUhA)

I am only getting this page but when click on login or signup it shows "global is not defined".
I am not familiar with AWS and I have no idea how I can solve it , if any one know the solution please let me know.

**Comment by VedangKanade20** [comment]
> > I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY0NDksIm5iZiI6MTcxODAwNjE0OSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNlZjViM2QzNTE1Njc2NmE4Njk1MzljMDcxYjE1Njc0MjQ4YTBkZjU1OTJmOGE1ZDI0NzcxNjE1YTI0ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msGpmd4QB8iKZjjt0WBJDtsyslxenCrrGeWyxcNoOmA)
> 
> > I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY0NDksIm5iZiI6MTcxODAwNjE0OSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNlZjViM2QzNTE1Njc2NmE4Njk1MzljMDcxYjE1Njc0MjQ4YTBkZjU1OTJmOGE1ZDI0NzcxNjE1YTI0ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msGpmd4QB8iKZjjt0WBJDtsyslxenCrrGeWyxcNoO
> 
> > I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY1MzksIm5iZiI6MTcxODAwNjIzOSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Nzc5OWQ5MGNlZGMxNjIxYjk1YWM5ZDliNGU1OTFlNDM0Njg5NTBhMDM5NjAxYzA2ZWZhMDQ5YTFkNDZjZGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1HTkj3TETZzw343fOZT-1Y1LsRGGCKwrklmlwi-lUhA)
> 
> I am only getting this page but when click on login or signup it shows "global is not defined". I am not familiar with AWS and I have no idea how I can solve it , if any one know the solution please let me know.

That isssue is the only issue I am facing rest i was able to do
(same reason unfamiliarity with AWS)

**Comment by VimalBharti99** [comment]
> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDY5NTAsIm5iZiI6MTcxODAwNjY1MCwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwODA0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2MzOThkZWZlMDk5MGRlNjY3NzkxMzQxMzgwMWJiMThlZjdkMDgwYTliOWNlODgzNmU2ODUxY2VmN2Q4ZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WYg_4MPaOygkY_mrEpw2MXWZ9ochCUfzJVhLVPea84)

what about AWS error?

**Comment by Miran-Firdausi** [comment]
I don't think it's an AWS error. On inspecting the console, we can find that client_id is missing for the OAuth authorization. Either we have to register this project for OAuth by our own or ask the project owner to provide the example OAuth client_id

**Comment by Miran-Firdausi** [comment]
So i fixed it guys, you have to first register for google OAuth and get the client it. here are the steps to follow: https://www.descope.com/blog/post/oauth2-react-authentication-authorization

Next create another .env file for client and copy and set the variable VITE_CLIENT_ID. And the error should go away.

**Comment by Miran-Firdausi** [comment]
Now we face another issue to use grant engine's email address. We can't use any random email ending with @grantengine.com as well, as it sends email to that address for verification.

Can somebody tell me where to access grantengines's email address or we are allowed to change the code to bypass this condition

**Comment by ashutosh7891** [comment]
> I was able to run the project guys Install the dependences first in client folder and in server folder simultaneously or one at a time but do it differently in both the folders Now make sure to place the env file not in route folder but in the server folder itself Now make sure you enter the details in env file correctly and now connect it to your mongodb ![Screenshot (54)](https://private-user-images.githubusercontent.com/123882577/338091300-dfaa98cc-6c8d-46bf-a7aa-bed3d3e6c01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDYyNTUsIm5iZiI6MTcxODAwNTk1NSwicGF0aCI6Ii8xMjM4ODI1NzcvMzM4MDkxMzAwLWRmYWE5OGNjLTZjOGQtNDZiZi1hN2FhLWJlZDNkM2U2YzAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwNzUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTk1MzE2YjEzYWU0MDdkNjhiNDBkMzU5ZDZmNWQ1ZThiNzUyODY2NTU5NTI4YTM5NWExOTBlODViNDQzMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ToHVteXKsErMqokSoQJQoWFWMftSfhxxh3JTaIw4gR8)

what details should i write inside my .env file ?

**Comment by Miran-Firdausi** [comment]
I figured out we need, these many variables
for server .env file
PORT=5000
MONGO_URL=mongodb://127.0.0.1:27017
JWT_SECRET=*write-some-random-secret*
SITE_URL=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=
MAIL_EMAIL=
MAIL_SECRET=


for client .env file
VITE_CLIENT_ID=*your-client-id*

We can not proceed until we receive all the information from them.

**Comment by MurtAz2001** [comment]
> I figured out we need, these many variables for server .env file PORT=5000 MONGO_URL=mongodb://127.0.0.1:27017 JWT_SECRET=_write-some-random-secret_ SITE_URL= AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= S3_BUCKET_NAME= MAIL_EMAIL= MAIL_SECRET=
> 
> for client .env file VITE_CLIENT_ID=_your-client-id_
> 
> We can not proceed until we receive all the information from them.

I have message them for details.

**Comment by vickky122** [comment]
what about aws error??

**Comment by Rohit16002** [comment]
I am also Unable to run this app. need your help
